-- liquibase formatted sql

-- changeset weare4saken:2
CREATE TABLE bid (
     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     bidder_name VARCHAR(64) NOT NULL,
     bid_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
     lot_id BIGINT NOT NULL REFERENCES lot(id)
);